export const reportMapping = [
  {
    text: "Coping with Adversity (Staying positive and composed under pressure)",
    high: "The result of the assessment is very good which indicates that when it comes to overcoming challenges during competitions you are able to keep going. This is a good sign as it suggests that adversities usually don't shake your self belief. Players must learn to overcome adversities as they are a part and parcel of sport. Staying calm in the face of challenges, maintaining emotional control, and staying positive are a few skills important for coping with adversity. Sharpening these skills will help you in becoming a mentally tough player.",
    average:
      "The result of the assessment suggests that you have a moderate ability to handle setbacks and challenges, but your responses to adversity may be inconsistent. At times, you are able to stay composed and focused in difficult situations, but there are moments when frustration, self-doubt, or external pressure can negatively impact your performance. You might recover quickly from some mistakes, yet struggle to bounce back from others, especially in high-stakes scenarios or when things don’t go as planned.",
    low: "The result of the assessment is average which indicates that you must build better coping skills to face adversity. It shows that when faced with adversity you may doubt your skills and become distracted with negative thoughts which hamper your performance. Players must learn to overcome adversities as they are a part and parcel of sport. Staying calm in the face of challenges, maintaining emotional control, and staying positive are a few skills important for coping with adversity. Developing these skills will help you in becoming a mentally tough player",
  },
  {
    text: "Coachability (Ability to accept and apply feedback)",
    high: "The result of the assessment is very good which indicates that you learn from mistakes and work to improve. It also suggests that you listen to your coach and accept feedback well. Showing willingness to listen and learn, accepting feedback and being grateful are few skills essential to become a coachable player. Sharpening these skills will help you make the most of your training and grow into a strong player.",
    average:
      "The result of the assessment suggests that you are generally open to feedback and willing to learn, but there may be times when you struggle to fully accept criticism or implement suggestions from coaches. You likely respond well to instruction in most situations, but in moments of frustration or doubt, you might become resistant to feedback or find it difficult to adjust your approach. This could stem from a desire to prove yourself independently, uncertainty about the feedback received, or difficulty making immediate changes in response to coaching advice",
    low: " The result of the assessment suggests that you may struggle with accepting feedback, making adjustments based on coaching advice, or maintaining a positive attitude when receiving constructive criticism. You might find it challenging to trust the guidance given by coaches, feel defensive when corrections are made, or prefer to rely on your own instincts rather than external input. This could sometimes lead to missed opportunities for growth, as implementing feedback is crucial for skill development and performance improvement.",
  },
  {
    text: "Concentration (Maintaining focus despite distractions)",
    high: "The result of the assessment suggests that you have a strong ability to maintain focus and stay engaged during training and competition. You are likely able to block out distractions, stay present in the moment, and direct your attention toward the task at hand, even in high-pressure situations. Your ability to concentrate allows you to make quick, effective decisions and remain composed, which can be a significant advantage in competitive environments.",
    average:
      "The result of the assessment is good which indicates that you are able to concentrate well in most competitive situations. However when negative thoughts enter your mind you may struggle to focus on your performance. Paying attention to the right cues, focusing on the present, and handling distractions are important skills essential for concentration. Sharpening these skills will help you enhance the quality of your performance",
    low: "The result of the assessment indicates that you need improvement in building your concentration skills. It means that you tend to get distracted by unwanted thoughts, either by internal or external distractors. When you lose concentration it becomes hard to execute your skills. Paying attention to the right cues, focusing on the present, and handling distractions are important skills essential for concentration. Sharpening these skills will help you enhance the quality of your performance. ",
  },
  {
    text: "Confidence & Achievement Motivation (Self-belief and motivation to succeed)",
    high: "The result of the assessment is very good  which indicates that you are usually confident of your skills and abilities. Your confidence and motivation to succeed help you in taking your performance to the next level. Trusting your talents and skills, feeling confident of your performance and being driven to achieve your goals are important skills that help you progress in your sport. Sharpening these skills will help you perform. ",
    average:
      "The result of the assessment is good which indicates that you are confident of your abilities however when things become challenging you tend to doubt your skills. Your motivation drops when you fail to achieve the targets and need time to get back. Trusting your talents and skills, feeling confident of your performance and being driven to achieve your goals are important skills that help you progress in your sport. Sharpening these skills will help you perform",
    low: "The result of the assessment suggests that you may struggle with self-belief and maintaining a strong drive to achieve your athletic goals. You might experience self-doubt before or during competitions, questioning your abilities and feeling uncertain about your performance. This can lead to hesitation, fear of failure, or a tendency to play it safe rather than take calculated risks. A lower score in this area may also indicate that you find it difficult to stay consistently motivated, especially after setbacks or when progress seems slow. You might rely on external validation—such as praise from coaches or results in competition—rather than having an internal sense of confidence and purpose driving you forward.",
  },
  {
    text: "Goal Setting & Mental Preparation (Planning and setting performance goals)",
    high: "The result of the assessment suggests that you have a strong ability to set clear objectives and mentally prepare for training and competition. You likely approach your sport with a well-defined plan, ensuring that each practice session and match contributes to your overall progress. Your ability to set specific, measurable, and realistic goals helps keep you motivated and focused, allowing you to track improvements over time. ",
    average:
      "The result of the assessment is good, which indicates that you set goals for performance; however you need guidance in setting the right goals for practice and competitions. While setting goals it is important to analyse current performance and set targets accordingly in order to increase your motivation. Setting goals and mentally preparing for performance are two of the most important mental skills required to achieve best performance. Sharpening these skills will give you a mental advantage and push you towards achieving success.",
    low: "The result of the assessment indicates that you may struggle with setting clear objectives, maintaining focus, and preparing yourself mentally for competition. This could mean that you enter training sessions or competitions without a well-defined plan, making it harder to stay motivated and track progress. You might also find it challenging to stick to long-term goals or adjust your mindset when faced with setbacks. Without structured mental preparation, you may feel uncertain about your approach, leading to inconsistency in performance and difficulty staying composed under pressure",
  },
  {
    text: "Peaking Under Pressure (Performing well in high-stakes situations)",
    high: "The result of your assessment is very good which indicates that you are able to take pressure positively. It means that you don't fear pressure and feel confident of using appropriate strategies to cope in pressure situations. Pressure is an inevitable part of sport. It is important to learn to embrace pressure, perceive pressure positively and learn ways to adjust and adapt to pressure situations in order to perform. Sharpening these mental skills will allow you to peak under pressure.",
    average:
      "The result of your assessment suggests that while you can handle pressure reasonably well, your performance in high-stakes situations is inconsistent. At times, you may thrive under pressure and deliver strong performances, but in other instances, nerves or hesitation may impact your decision-making and execution. You might feel tense or anxious before important moments, and while you usually settle into the competition, the initial pressure can sometimes affect your confidence. Your ability to perform under pressure may depend on external factors like crowd support, coaching feedback, or early success in a match, rather than a consistently strong internal mindset.",
    low: "The result of your assessment indicates that you need improvement in learning to perform under pressure. It means that you tend to avoid pressure as you fear facing it. Your performance may be severely affected as you focus on your inability to cope and feel incompetent. Pressure is an inevitable part of sport. It is important to learn to embrace pressure, perceive pressure positively and learn ways to adjust and adapt to pressure situations in order to perform. Building these mental skills will allow you to peak under pressure.",
  },
  {
    text: "Freedom from Worry (Managing anxiety and not dwelling on mistakes)",
    high: "The result of your assessment is very good which indicates that you think positively in most competitive situations. This is a great sign as it suggests that you can channel negative thoughts or worries and stay mentally calm during pressure. Thinking positive, focusing on the present, overcoming worries and being self confident are a few mental skills that enhance your performance. Sharpening these skills will help you think clearly and make better decisions during performance. Practicing mental training regularly and building on your mental capacities will help you perform consistently every single time.",
    average:
      "The result of your assessment is average which shows that you tend to worry about the outcome of your performance. It means that you often experience negative thoughts that interfere with your ability to concentrate as you get distracted by worries about loss or failure. Thinking positive, focusing on the present, overcoming worries and being self confident are a few mental skills that enhance your performance. Sharpening these skills will help you think clearly and make better decisions during performance. Practicing mental training regularly and building on your mental capacities will help you perform consistently every single time.",
    low: "The result of your assessment shows that you need improvement in reducing worries and utilizing your thinking skills effectively in competitive situations. It means that you tend to worry about your game, and experience more negative thoughts about your ability to achieve success which becomes an obstacle in your performance. Thinking positive, focusing on the present, overcoming worries and being self confident are a few mental skills that enhance your performance. Sharpening these skills will help you think clearly and make better decisions during performance. Practicing mental training regularly and building on your mental capacities will help you perform consistently every single time.",
  },
];
